### PR TITLE
Feature/update cnx address

### PR DESCRIPTION
**Pull request by akexorcist**
Update new contact address of Nextzy Chiang Mai

### CODE REVIEW

**Review by Thongpak21 — APPROVED** [review]
LGTM!

**Review by Thongpak21 — APPROVED** [review]
LGTM

**Review by Thongpak21 — APPROVED** [review]
LGTM again.

**Review by akexorcist — COMMENTED** [review]
Woohoo!

**Review by Thongpak21 — APPROVED** [review]

**Review by Tanapruk — COMMENTED** [review]
LGTM

**Comment by akexorcist** [comment]
LGTM

**Pull request merged**
